[features]
seeds = false
skip-lint = true

[programs.localnet]
agentreputation_dao = ""

[programs.devnet]
agentreputation_dao = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "node scripts/initialize.js"
register = "node scripts/register.js"
vouch = "node scripts/vouch.js"
